---
name: HTML-LinkList
version: 0.09
author:
  - Kathryn Andersen
abstract: Create a 'smart' list of HTML links.
license: perl
build_requires:
  Test::More: 0
provides:
  HTML::LinkList:
    file: lib/HTML/LinkList.pm
    version: 0.09
generated_by: Module::Build version 0.2611
